### ISSUE TITLE
 物品 randomMaterial_1(罗德岛物资补给) 数量不符合企鹅数据验证规则

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#105]
资源补给和应急理智小样都不行，我看企鹅物流给的上下限都是1 ~~这真的没问题吗~~，我暂时没找到那个验证写在哪里

**Comment by dantmnf** [comment]
https://penguin-stats.io/PenguinStats/api/limitations 里没有返回这两个道具的上下限，这里就认为不会掉落这两个了（

**Comment by LittleNightmare** [comment]
> https://penguin-stats.io/PenguinStats/api/limitations 里没有返回这两个道具的上下限，这里就认为不会掉落这两个了（

的确，但是randomMaterial_1(罗德岛物资补给)可以找到啊

**Comment by dantmnf** [comment]
这个是统计箱子里开出了什么的

**Comment by LittleNightmare** [comment]
> 这个是统计箱子里开出了什么的

还行，我已经反馈了 penguin-statistics/frontend-v2#175
