### ISSUE TITLE
[BUG] 无法判断行动结束

### ISSUE THREAD

**Issue by L0snight** [ninthDevilHAUNSTER/ArknightsAutoHelper#106]
在使用过程中，只能代理一次，结束受就无法判断关卡结束。如下图：
![image](https://user-images.githubusercontent.com/19932520/71637439-6b8b1580-2c7e-11ea-8a2a-079f16be925c.png)
环境：
夜神模拟器 6.5.0.3，分辨率1280*720，开发者模式已经打开
win10

**Comment by LittleNightmare** [comment]
先把log文件夹里的.log文件和drop-recognition.html发上来

**Comment by dantmnf** [comment]
> 
> 
> 先把log文件夹里的.log文件和drop-recognition.html发上来

还没到这，应该发一下游戏/模拟器的截图

**Comment by L0snight** [comment]
release版:
模拟器截图：
![image](https://user-images.githubusercontent.com/19932520/71638106-d7c34480-2c91-11ea-8969-d93668790b8b.png)
顺便提一下，这个剩余理智也不对，总是显示70，实际上是102
![image](https://user-images.githubusercontent.com/19932520/71638114-017c6b80-2c92-11ea-85ae-d4773917c384.png)

**Comment by dantmnf** [comment]
当前 master/dev 分支上的版本可以正常识别这个截图。
release 上的还没更新（

**Comment by L0snight** [comment]
感谢！master分支正常。不过似乎有几个模块不支持pyhton 3.8？opencv-python 在pyhton 3.8环境下无法正常安装。

**Comment by dantmnf** [comment]
尝试更新 pip:

    python -m pip -U pip
