### ISSUE TITLE
任务清单功能问题

### ISSUE THREAD

**Issue by Drkyoko** [ninthDevilHAUNSTER/ArknightsAutoHelper#11]
说明中提到任务清单支持click_location.LIZHI_CONSUME下关卡
其实应该是支持click_location.CLICK_LOCATION下的关卡

任务清单功能做拖动和点击后，偶尔会错过之后的点击或者拖动，可能是因为模拟器卡顿。

**Comment by ninthDevilHAUNSTER** [comment]
确实是这样，关于战斗选关我之后还会增加。关于逻辑判断的话之后会补全，现在先加一些注释了

目前 简略战斗模块 的功能已经基本完善了。

**Comment by ninthDevilHAUNSTER** [comment]
有啥后续的问题和改进的想法的话咱可以群里说鸭~~~~
