### ISSUE TITLE
官方对辅助工具的态度？

### ISSUE THREAD

**Issue by NadiaSama** [ninthDevilHAUNSTER/ArknightsAutoHelper#110]
请问一下使用这个辅助工具会导致官方封账号么？

**Comment by dantmnf** [comment]
TL; DR 灰色地带。可能违反用户协议，未有封号先例。 ~~你去跳脸除外~~

<details><summary>用户协议相关条文</summary>

> 6.2 除非适用法律允许或鹰角网络事先书面同意，您不得在使用鹰角网络游戏软件和鹰角网络游戏服务过程中实施以下行为：
> 　...
> 　14\) 通过非鹰角网络开发的或未经授权的第三方软件、插件、外挂、系统，使用鹰角网络游戏软件及鹰角网络游戏服务，或制作、发布、传播任何形式的妨碍游戏公平性的辅助工具或程序（您同意以游戏程序中的监测数据和异常表现作为判断用户是否存在使用非法外挂等方法的行为）；
> 　15\) ...
> 　16\) 对游戏或服务过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据，以及软件运行所必需的系统数据，进行复制、修改、增加、删除、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非经合法授权的第三方工具/服务接入软件和相关系统；
> 　...
> 　19\) 其他任何有违适用法律规定、本协议约定，或在行业内被广泛认为属于不正当行为，或其他不利于鹰角网络游戏和其他用户的行为。
</details>

**Comment by ninthDevilHAUNSTER** [comment]
小伙纸~咱们这是个高等级的连点器，而不是外挂。

> 14) 通过非鹰角网络开发的或未经授权的第三方软件、插件、外挂、系统，使用鹰角网络游戏软件及鹰角网络游戏服务，或制作、发布、传播任何形式的妨碍游戏公平性的辅助工具或程序（您同意以游戏程序中的监测数据和异常表现作为判断用户是否存在使用非法外挂等方法的行为）；

我们没有妨碍游戏的公平性。游戏的监测数据从来没有检测到我们存在所谓的异常操作。我们自开发这款辅助以来，在群里没有一位仁兄汇报自己被官方封号。

> 16) 对游戏或服务过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据，以及软件运行所必需的系统数据，进行复制、修改、增加、删除、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非经合法授权的第三方工具/服务接入软件和相关系统；

我们没有对对内存进行修改。仅仅是通过识别当前屏幕的内容提升我们的游戏体验而已。

**Comment by NadiaSama** [comment]
> 小伙纸~咱们这是个高等级的连点器，而不是外挂。
> 
> > 1. 通过非鹰角网络开发的或未经授权的第三方软件、插件、外挂、系统，使用鹰角网络游戏软件及鹰角网络游戏服务，或制作、发布、传播任何形式的妨碍游戏公平性的辅助工具或程序（您同意以游戏程序中的监测数据和异常表现作为判断用户是否存在使用非法外挂等方法的行为）；
> 
> 我们没有妨碍游戏的公平性。游戏的监测数据从来没有检测到我们存在所谓的异常操作。我们自开发这款辅助以来，在群里没有一位仁兄汇报自己被官方封号。
> 
> > 1. 对游戏或服务过程中释放到任何终端内存中的数据、软件运行过程中客户端与服务器端的交互数据，以及软件运行所必需的系统数据，进行复制、修改、增加、删除、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非经合法授权的第三方工具/服务接入软件和相关系统；
> 
> 我们没有对对内存进行修改。仅仅是通过识别当前屏幕的内容提升我们的游戏体验而已。

咱们这个工具是通过`adb`来获得屏幕截图以及实现点击操作的吧。
