### ISSUE TITLE
碎石功能的问题

### ISSUE THREAD

**Issue by pingplug** [ninthDevilHAUNSTER/ArknightsAutoHelper#126]
系统：Arch Linux x86_64
模拟器：Anbox
OCR：tesseract 4.1.1
分支：dev

碎石功能发现了两个小问题：
1. 单`+R`选项无法开启碎石，必须和`+r`一起才能使用，似乎是回理智判断时只考虑了`use_refill`
2. 碎石失败会陷入死循环，在`helper.py`第315行加一句退出循环比较好

**Comment by dantmnf** [comment]
目前的回复逻辑是打开回复界面之后判断是否点击确定，不会点别的地方。
游戏的逻辑是有理智药就优先展示理智药，没有才展示碎石，所以只开碎石不开吃药而且还有药的话也不会点确定（~~不会真的有人放着理智药不吃去碎石吧，不会吧不会吧~~

第二个是已知问题
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/93feb52a1a3398b0f27ca93d6c2e782f80a37805/Arknights/helper.py#L309
当时做这个功能的时候没有这样的截图，欢迎提供截图。

**Comment by pingplug** [comment]
> 游戏的逻辑是有理智药就优先展示理智药，没有才展示碎石，所以只开碎石不开吃药而且还有药的话也不会点确定（不会真的有人放着理智药不吃去碎石吧，不会吧不会吧

建议要么`+R`同时开启药和碎石，要么在文档里说清楚要同时开启

> 当时做这个功能的时候没有这样的截图，欢迎提供截图。

来，来三张大块的

![screen_720](https://user-images.githubusercontent.com/6712475/86301232-ec2fcc00-bc37-11ea-9826-d45971f32003.png)
![screen_1080](https://user-images.githubusercontent.com/6712475/86301236-ef2abc80-bc37-11ea-9ea5-6c8698cc375c.png)
![screen_1440](https://user-images.githubusercontent.com/6712475/86301240-f0f48000-bc37-11ea-9d81-5c139a01e554.png)

**Comment by pingplug** [comment]
再给两块

![2400x1080](https://user-images.githubusercontent.com/6712475/86301974-e4712700-bc39-11ea-95fe-641c13aae4b8.png)
![2160x1080](https://user-images.githubusercontent.com/6712475/86301968-e0dda000-bc39-11ea-82c0-93313469cafd.png)

**Comment by pingplug** [comment]
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/7858c21563a61635325780e7775b0077453b7cdb/Arknights/shell_next.py#L57
这里导致单`+r`不能用药，`+rR`只能碎石
不如直接
```diff
             elif c == 'r':
                 if action is not None:
                     def op(helper):
                         helper.use_refill = action
+                        helper.refill_with_item = action
                     ops.append(op)
             elif c == 'R':
                 if action is not None:
                     def op(helper):
+                        helper.use_refill = action
                         helper.refill_with_originium = action
                     ops.append(op)
```
似乎代码其他地方也并没有限制`+R`只碎石不用药的用法

**Comment by dantmnf** [comment]
> 似乎代码其他地方也并没有限制+R只碎石不用药的用法

理智不足 -> 弹出回复界面 -> 默认选中“使用药剂恢复” -> `refill_type = 'item'` -> `refill_with_item == False` -> `confirm_refill = False`
~~当然再加个点击选中碎石也行~~
