### ISSUE TITLE
这个脚本支持雷电模拟器吗？

### ISSUE THREAD

**Issue by zhengzhouyang** [ninthDevilHAUNSTER/ArknightsAutoHelper#131]
这个脚本支持雷电模拟器吗？还是只支持MUMU模拟器？

**Comment by Artoria2e5** [comment]
自己看 README:
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/tree/dev#%E5%85%B3%E4%BA%8E%E4%B8%80%E4%BA%9B%E5%B8%B8%E8%A7%81%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by zhengzhouyang** [comment]
好的，谢谢。
