### ISSUE TITLE
不明原因引起的崩溃

### ISSUE THREAD

**Issue by My-stery** [ninthDevilHAUNSTER/ArknightsAutoHelper#138]
已知：release 20200808 版本基本能够复现错误 ，0912 GUI 版本不会出现此问题。
模拟器均为1280*720分辨率，ADB 版本为 36 。并且夜神模拟器 与 mumu模拟器 均能够复现此错误。
必须重启模拟器才能消除此错误。

**程序报错如图：**
![image](https://user-images.githubusercontent.com/34577331/90338003-176c5000-e019-11ea-8b2c-f12e67bb092a.png)

复现步骤：

1. 模拟器启动后先进行一次简略战斗。
2. 稍微等一小段时间。
3. 再次进行简略战斗时产生错误。

[附上 Log 文件打包](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/files/5080979/log.zip)

感谢您的助手护住了各位博士的肝（｀ 3′）

**Comment by dantmnf** [comment]
该问题目前已经修复，请尝试 Actions 中的版本。

**Comment by My-stery** [comment]
> 该问题目前已经修复，请尝试Actions中的版本。

感谢！！
