### ISSUE TITLE
满级后识别失败

### ISSUE THREAD

**Issue by pingplug** [ninthDevilHAUNSTER/ArknightsAutoHelper#140]
log:

![index](https://user-images.githubusercontent.com/6712475/91684420-0c253280-eb8a-11ea-868d-a8d139352159.png)
![index1](https://user-images.githubusercontent.com/6712475/91684429-11827d00-eb8a-11ea-8eb5-83545e7dfda2.png)

[('理智返还', 0.08955306), ('幸运掉落', 0.07034944), ('常规掉落', 0.060515467), ('1.2倍声望&龙门币奖励', 0.053213596), ('特殊掉落', 0.05267052), ('报酬', 0.045116305), ('1.0倍声望&龙门币奖励', 0.035352003), ('首次掉落', 0.01379231), ('额外物资', 0.0033784388), ('end', -0.06077118), ('friendship', -0.07048219)]

group has 1 items

**Comment by pingplug** [comment]
![screen_1280x720](https://user-images.githubusercontent.com/6712475/91685146-0d575f00-eb8c-11ea-9127-7c20a7e962cd.png)
![screen_1920x1080](https://user-images.githubusercontent.com/6712475/91685151-10524f80-eb8c-11ea-9e7b-12e26d980187.png)
![screen_2560x1440](https://user-images.githubusercontent.com/6712475/91685152-11837c80-eb8c-11ea-99c5-0cc2747814d2.png)
提供三种分辨率的截图

**Comment by pingplug** [comment]
![screen](https://user-images.githubusercontent.com/6712475/91685415-d9c90480-eb8c-11ea-8907-c3b2e28ca5fe.png)
再提供一张两星的截图

**Comment by pingplug** [comment]
还是识别失败，对比了一下，发现是模板的图片黑边没裁干净，缩放之后模板的字比实际的字小
既然模板是从游戏里截的，可以让模板和图片都经过同样的`crop_blackedge()`函数处理一下

**Comment by dantmnf** [comment]
模板是已经经过 crop_blackedge 处理的，可能是 720 分辨率下文字太糊导致切多了（

~~而且你给的四张图全部通过测试了~~

**Comment by dantmnf** [comment]
现在改成不切黑边直接 match template，再不行估计就要上 SIFT/FLANN 或者 tesseract 了（

**Comment by pingplug** [comment]
720p分辨率下连续8次没有任何问题，我先关了
