### ISSUE TITLE
有没有可能支持云游戏

### ISSUE THREAD

**Issue by mashirozx** [ninthDevilHAUNSTER/ArknightsAutoHelper#142]
比如[网易云游戏](https://cg.163.com/#/mobile)

想在pi上挂机，但是没法装模拟器，我想既然是基于ocr的，那么用浏览器运行的游戏要兼容也不难吧 :)

**Comment by Nchyn** [comment]
文字识别基于OCR，但截图，模拟点击基于ADB
嗯。。。只要服务商提供ADB端口（多半不行

**Comment by mashirozx** [comment]
hh好吧
