### ISSUE TITLE
剿灭结束无法识别

### ISSUE THREAD

**Issue by debugAllTheTime** [ninthDevilHAUNSTER/ArknightsAutoHelper#143]
使用的baidu ocr的接口
但是无法识别剿灭结束
![Screenshot_20200928-084231](https://user-images.githubusercontent.com/25170510/94380943-170fba80-016a-11eb-9b3a-92d1f8c15a9b.png)
![Snipaste_2020-09-28_08-42-40](https://user-images.githubusercontent.com/25170510/94380958-1f67f580-016a-11eb-880c-9d9e9e42f966.png)

**Comment by kooWZ** [comment]
+1
