### ISSUE TITLE
希望能把各个点击坐标分离出来，然后就可以不绑定模拟器了

### ISSUE THREAD

**Issue by fan624009652** [ninthDevilHAUNSTER/ArknightsAutoHelper#17]
直接使用手机开发者模式也可以adb调试啊，没有必要非得用模拟器
不过各个游戏内的坐标会出问题，这个可以让大家来贡献不同型号的手机的不同坐标，只要分离出来作为一个配置文件就好了，目前看来各个坐标文件还是硬编码在代码里的

**Comment by fan624009652** [comment]
还有作者你的小日记怎么日期都写的2018年的...

**Comment by ninthDevilHAUNSTER** [comment]
18年就当个彩蛋吧，对就是这样...
坐标配置文件的话之后会抽取成JSON格式的。开发者模式理论上是可行的，我精力有限还没有DEBUG。所以把手机连上电脑来搞的想法还是很不错的。

群里有童鞋说希望全部改成相对坐标点，不知道这样的玩法是否可行。

**Comment by fan624009652** [comment]
相对坐标点我觉得够呛，我自己就在游戏公司上班，不同的机型并不是简单的等比例拉伸，有的时候要针对不同的机型调整位置，所以最好还是抽出配置文件来...

**Comment by fan624009652** [comment]
连手机adb我已经弄通了跟模拟器没差，不过由于你那个坐标全都是乱的也没法用

**Comment by wdjwxh** [comment]
用模拟器是为了拯救我的电池
