### ISSUE TITLE
使用新功能刷库存中最少的蓝材料出现BUG

### ISSUE THREAD

**Issue by davidelectricfree** [ninthDevilHAUNSTER/ArknightsAutoHelper#187]
+] 请选择需要的功能：5
[!] 正在准备提供服务

grass_on_aog.py
==================================================================================================
长草时用的脚本, 检查库存中最少的蓝材料, 然后去 aog 上推荐的地图刷材料.
aog 地址: https://arkonegraph.herokuapp.com/

不想的刷的材料可以修改脚本中的 exclude_names.

cache_key 控制缓存的频率, 默认每周读取一次库存, 如果需要手动更新缓存,
直接删除目录下的 aog_cache.json 和 inventory_items_cache.json 即可.

只刷常规关卡, 活动关卡不刷.

可以尝试将 config/config.yaml 中的 behavior/use_ocr_goto_stage 修改为 true 以支持更多的关卡跳转
==================================================================================================

不刷以下材料: ['固源岩组', '凝胶', '炽合金', '晶体元件']
 Ξ 确认设备名称：127.0.0.1:7555
加载库存信息...
require item: 研磨石, owned: 0
aog stage: 4-8
 Ξ 正在返回主页
 Ξ 发现返回按钮，点击返回
 Ξ 发现返回按钮，点击返回
 Ξ 已回到主页
 Ξ 进入作战
 Ξ 未能定位关卡地图
Traceback (most recent call last):
  File "C:\Users\xxxxx\Documents\GitHub\ArknightsAutoHelper\grass_on_aog.py", line 115, in <module>
    helper.module_battle(stage, 1000)
  File "C:\Users\xxxxx\Documents\GitHub\ArknightsAutoHelper\Arknights\helper.py", line 530, in module_battle
    self.goto_stage(c_id)
  File "C:\Users\xxxx\Documents\GitHub\ArknightsAutoHelper\Arknights\helper.py", line 704, in goto_stage
    self.find_and_tap('episodes', path[1])
  File "C:\Users\xxxxx\Documents\GitHub\ArknightsAutoHelper\Arknights\helper.py", line 603, in find_and_tap
    raise RuntimeError('recognition failed')
RuntimeError: recognition failed

界面卡在章节选择那里，不知道是不是和我只打到第五章有关，但是理论上来说，虽然打到第五章，应该不影响打4-8。

另外还有一个建议，在进行公开招募的关键词OCR时，有的时候第一遍出错的几率较大，看能不能程序检测到OCR失败后（有时候OCR会少识别中间某个字），即对OCR的结果进行检查（因为TAG是固定的，主要检查缺字或者错字），如果正确则放出，如果不匹配，自动重新OCR，再将正确的结果输出。

**Comment by CJN96** [comment]
未能定位关卡地图是因为没有启用 ocr 关卡跳转吧.

项目 config 文件夹里面有个 config.yaml 文件, 将里面的 use_ocr_goto_stage 改成 true 再试试?

**Comment by davidelectricfree** [comment]
> 
> 
> 未能定位关卡地图是因为没有启用 ocr 关卡跳转吧.
> 
> 项目 config 文件夹里面有个 config.yaml 文件, 将里面的 use_ocr_goto_stage 改成 true 再试试?

把 config-template.yaml 和 config.yaml 文件里面你说的 use_ocr_goto_stage 均改成 true 以后，还是会报错。下面是改过以后的报错。

[+] 请选择需要的功能：5
[!] 正在准备提供服务

grass_on_aog.py
==================================================================================================
长草时用的脚本, 检查库存中最少的蓝材料, 然后去 aog 上推荐的地图刷材料.
aog 地址: https://arkonegraph.herokuapp.com/

不想的刷的材料可以修改脚本中的 exclude_names.

cache_key 控制缓存的频率, 默认每周读取一次库存, 如果需要手动更新缓存,
直接删除目录下的 aog_cache.json 和 inventory_items_cache.json 即可.

只刷常规关卡, 活动关卡不刷.

可以尝试将 config/config.yaml 中的 behavior/use_ocr_goto_stage 修改为 true 以支持更多的关卡跳转
==================================================================================================

不刷以下材料: ['固源岩组', '凝胶', '炽合金', '晶体元件']
 Ξ 确认设备名称：127.0.0.1:7555
加载库存信息...
require item: 研磨石, owned: 0
aog stage: 4-8
 Ξ 正在返回主页
 Ξ 发现返回按钮，点击返回
 Ξ 已回到主页
 Ξ 进入作战
 Ξ 未能定位关卡地图
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\Documents\GitHub\ArknightsAutoHelper\grass_on_aog.py", line 115, in <module>
    helper.module_battle(stage, 1000)
  File "C:\Users\xxxxxxx\Documents\GitHub\ArknightsAutoHelper\Arknights\helper.py", line 528, in module_battle
    self.goto_stage_by_ocr(c_id)
  File "C:\Users\xxxxxx\Documents\GitHub\ArknightsAutoHelper\Arknights\helper.py", line 721, in goto_stage_by_ocr
    self.find_and_tap('episodes', path[1])
  File "C:\Users\xxxxx\Documents\GitHub\ArknightsAutoHelper\Arknights\helper.py", line 603, in find_and_tap
    raise RuntimeError('recognition failed')
RuntimeError: recognition failed

**Comment by CJN96** [comment]
是卡在选章节的那个界面吗?

https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/0ce17f27724a4e2d2eb9caab8960fa4fe4d3dc14/resources/imgreco/map_vectors.py#L40

试试把这行改成:

```python
map_anchors['episodes'] = ['ep%02d' % x for x in range(8)]
```

**Comment by davidelectricfree** [comment]
这样可以运行成功，谢谢。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by davidelectricfree** [comment]
> 是卡在选章节的那个界面吗?
> 
> https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/0ce17f27724a4e2d2eb9caab8960fa4fe4d3dc14/resources/imgreco/map_vectors.py#L40
> 
> 试试把这行改成:
> 
> ```python
> map_anchors['episodes'] = ['ep%02d' % x for x in range(8)]
> ```

这样可以运行成功，谢谢。
