### ISSUE TITLE
明日方舟2021.4.15的ui更新会影响脚本运行嘛

### ISSUE THREAD

**Issue by creeper121386** [ninthDevilHAUNSTER/ArknightsAutoHelper#190]
rt，俺没细看python代码，但既然用到了OCR的话，应该是对固定区域做识别。然鹅，今天下午明日方舟更新了新的游戏界面，那么脚本是不是也得跟着改改识别区域的坐标

**Comment by RikkaBlue** [comment]
我的 `quick` 正常使用。
不过因为有新素材，会有未识别的，（我太菜了不知道怎么更新）

**Comment by ninthDevilHAUNSTER** [comment]
不影响 quick命令，因为战斗流程，自动回体力等UI均没有改变。auto命令可能会有问题。

**Comment by creeper121386** [comment]
ok，蟹蟹老哥
