### ISSUE TITLE
没有办法兼容 Linux 吗？

### ISSUE THREAD

**Issue by RikkaBlue** [ninthDevilHAUNSTER/ArknightsAutoHelper#194]
看到 `requirements` 里面写死系统要求 `win32`。
~~主要有用服务器 adb 连手机挂机的扭曲想法~~

**Comment by duzhaokun123** [comment]
实测 Linux 可用
`win32`什么的无视掉

**Comment by RikkaBlue** [comment]
好的，谢谢。
直接删掉就行了吧。
