### ISSUE TITLE
GUI版 计数错误 数据类型错误 自动回复理智无效

### ISSUE THREAD

**Issue by Haku247** [ninthDevilHAUNSTER/ArknightsAutoHelper#195]
1.计数错误
共计应31次作战，已完成4次，应剩余27次战斗。
![image](https://user-images.githubusercontent.com/20238213/115952105-de28a000-a516-11eb-8a84-e6e05ffad73f.png)

2.数据类型错误
手动输入作战次数后，需要进行一次int型强制数据转化，否则会被识别为str
![image](https://user-images.githubusercontent.com/20238213/115952155-0e703e80-a517-11eb-9ab9-aaddb9bcd921.png)

3.自动回复理智失效
使用道具回复和使用源石回复的选项未能发挥作用。
![image](https://user-images.githubusercontent.com/20238213/115952228-5d1dd880-a517-11eb-82a3-8ed82242e9d1.png)

**Comment by dantmnf** [comment]
计数那个可能存在个人理解差异：退出的时候程序已经进入到第 5 次作战逻辑内，所以不计算进剩余数量。

**Comment by Haku247** [comment]
你这样说虽然没有问题，但是从用户角度考虑，用户设置了30次作战，目的是刷30次副本拿到30次奖励。再加上脚本中包括了自动储存进度的功能。如果多次因理智不足中断，最后就会少很多次。所以作战次数最好还是用实际运行了多少次脚本，以免引起误解。

我是之前在arknight tool网站根据企鹅物流计算好总计的刷本次数，然后填进去跑的。

在 2021年4月24日，18:11，dantmnf ***@***.***> 写道：

﻿

计数那个可能存在个人理解差异：退出的时候程序已经进入到第 5 次作战逻辑内，所以不计算进剩余数量。

**Comment by Haku247** [comment]
问题已被解决
