### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by Shimada666** [ninthDevilHAUNSTER/ArknightsAutoHelper#2]
系统有对点击时间间隔,点击位置进行检测么

**Comment by ninthDevilHAUNSTER** [comment]
目前主战斗部分（就是从点“开始战斗”按钮开始），所有的点击位置已经随机化。对应函数模块为 `module_battle_slim()`。目前比较推荐用这个函数，因为我知道你在刷精二材料。你只要人工定位到战斗开始这个按钮就可以。具体参考在arknights 目录下的README.md。

点击时间间隔也是随机化的，可以参考 `self.__wait()` 函数
