### ISSUE TITLE
快速战斗模块指定关卡运行报错

### ISSUE THREAD

**Issue by fatinghenji** [ninthDevilHAUNSTER/ArknightsAutoHelper#206]
#### 我做了什么？
- [x] 阅读了使用文档
- [ ] 重新看了一遍Wiki   :see_no_evil:~~没看到本项目有Wiki~~
- [x] 尝试使用了最新版本
- [x] 尝试了在已有的issue里面找答案  
-  在https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/issues/160  看到了类似的问题，@Sait0Yuuki也做出了回答，但是我在使用2进制版本，不知道应该怎么修改文件
- [ ] 去问谷歌/度娘   
#### 使用环境
- [x] 手机端：安卓11
- [x] 电脑端：Windows10
#### 报错代码如下
```ruby
Exception in RPC invocation
Invocation: {"action":"worker:module_battle","args":["1-7",1]}
RuntimeError: recognition failed

Details
  File "webgui2\worker.py", line 89, in run
  File "webgui2\worker.py", line 146, in decorated
  File "webgui2\worker.py", line 55, in <lambda>
  File "Arknights\helper.py", line 564, in module_battle
  File "Arknights\helper.py", line 786, in goto_stage
  File "Arknights\helper.py", line 638, in find_and_tap
```
#### 已经尝试的方案：
- [x] 重新下载解压
- [x] 更换ocr引擎
- [x] 重新链接手机
#### 复现办法
1、从任意界面启动指定管卡
2、成功返回主页
3、进入作战页面
#### 当前结果 
![image](https://user-images.githubusercontent.com/37131177/117319492-ee009680-aebd-11eb-87ae-cdacba66424d.png)

#### 期望目标
:sparkling_heart:按步骤执行期望关卡

**Comment by triwinds** [comment]
如果屏幕比例大于 16:9 可以试试将 config.yaml 里的 behavior/use_ocr_goto_stage 改成 true

**Comment by fatinghenji** [comment]
> 如果屏幕比例大于 16:9 可以试试将 config.yaml 里的 behavior/use_ocr_goto_stage 改成 true

问题解决了，谢谢。
