### ISSUE TITLE
更新之后helper.py line 324又出现"invalid literal for int() with base 10"了

### ISSUE THREAD

**Issue by FDrag0n** [ninthDevilHAUNSTER/ArknightsAutoHelper#230]
更新https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/commit/5977cb85a317f01045b4bd0675b15cecb5514bfb之后helper.py line 324又出现"invalid literal for int() with base 10"了 

imgreco/before_operation.py的101行无法正确得出剩余ap，比如我这里是85/135，他识别结果是" 85/1"

**Comment by dantmnf** [comment]
请提供一下出错时的识别日志（log/imgreco.before_ooeration）

**Comment by FDrag0n** [comment]
![image](https://user-images.githubusercontent.com/34733637/124413802-f5400580-dd83-11eb-969b-b2a3b68c0cd2.png)
分辨率为1280x720 180dpi
log打包
[log.zip](https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/files/6761453/log.zip)

**Comment by FDrag0n** [comment]
修改split勉强可用，但是理智和门票识别的recoresult['consume_ap']有点问题
![image](https://user-images.githubusercontent.com/34733637/124414145-ae9edb00-dd84-11eb-9f02-55660a70b1ae.png)
