### ISSUE TITLE
GUI使用过程中日志区域出现错误提示

### ISSUE THREAD

**Issue by Chunbear** [ninthDevilHAUNSTER/ArknightsAutoHelper#236]
![image](https://user-images.githubusercontent.com/34836688/126058099-54c4a41e-f2d7-44f9-b969-ffbf60766533.png)
关卡结束后识别掉落物品的时候出现的，但并不是每次都会出现。

**Comment by dantmnf** [comment]
参见 #234 #135

**Comment by Chunbear** [comment]
> 参见 #234 #135

感谢！
