### ISSUE TITLE
[feature request] 自动化公招

### ISSUE THREAD

**Issue by chunibyo-wly** [ninthDevilHAUNSTER/ArknightsAutoHelper#237]
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/projects/2#card-48537819

1. 请问这个有人正在做吗，有的话应该如何参与协作。
2. 请问选择tag的权重应该如何计算，通过贪心得到一个最优的的tag选择，有同学提供了一个评估指标[代码](https://github.com/shuangluoxss/ArkAutoHR/blob/ce9c15bf7353a7a143787c93ec7c351ae6bd6fd9/auto_hr.py#L147-L164)，视频在[这里](https://www.bilibili.com/video/BV1jh411k7r9)，是不是可以参考一下。

**Comment by yuanyan3060** [comment]
计算公招的策略已经有了。

**Comment by MistEO** [comment]
打个广告，吹一波自己的_(:з」∠)_
[MeoAssistance](https://github.com/MistEO/MeoAssistance)已经有自动公招了
