### ISSUE TITLE
baidu ocr bug 与 一些小问题

### ISSUE THREAD

**Issue by lxflxf56** [ninthDevilHAUNSTER/ArknightsAutoHelper#24]
![image](https://user-images.githubusercontent.com/19236906/60755386-8fe49d00-a021-11e9-96a8-1723725ab3a0.png)
不应该写成未检测到文本，直接空即可，并且words_result_num没有none判断，若未识别直接判0会异常，本想创建分支提上去的，但是不会弄，尴尬。

**Comment by lxflxf56** [comment]
同时理智的图片二值化会把数字给弄没，估计是二值化算法不好，用api的话我直接发原图都能识别，这可以改下

**Comment by lxflxf56** [comment]
还有望所有的内嵌对象调用都先检查下是不是None，我看有几处都没有做

**Comment by LittleNightmare** [comment]
> ![image](https://user-images.githubusercontent.com/19236906/60755386-8fe49d00-a021-11e9-96a8-1723725ab3a0.png)
> 不应该写成未检测到文本，直接空即可，并且words_result_num没有none判断，若未识别直接判0会异常，本想创建分支提上去的，但是不会弄，尴尬。

0会异常???也许是百度api接口改了，当时我返回给的是0。二值化算法我不是专业的，所以随便找了一个，也许用OpenCV会好一些，但是先不增加了库了。针对数字消失问题，可能是临界灰度值的问题，我试试调低点看看，但是....有可能是根本没截到数字，我试试弄个debug工具，帮忙确定一下问题。不过大概要等16个小时后，现在写完了，但没测试。None那个看看之后有木有空吧，咕咕咕

**Comment by LittleNightmare** [comment]
暂时测试不了,官服10.00-16.00更新，如果有需求，请联系我，我会传到我的branch上 ~~光明正大的咕咕咕~~

**Comment by LittleNightmare** [comment]
目前该问题我一直不知道怎么复现，我的百度ocr一直都是有0这个返回值，但已经改好了


> 还有望所有的内嵌对象调用都先检查下是不是None，我看有几处都没有做

这个出现问题再开新的issue吧
