### ISSUE TITLE
baidu ocr 其妙的识别错误

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#25]
在红豆背景的界面下，百度ocr只能识别出“动结束”

我打算改成识别“结束”，也许能暂时解决问题，但.......长期这样不知道行不行

~~文件没穿上来.....~~
文件在下图

**Comment by LittleNightmare** [comment]
![battle_end](https://user-images.githubusercontent.com/19811879/61480362-d613f780-a963-11e9-9eaf-46ba0fb1fa57.png)

**Comment by ninthDevilHAUNSTER** [comment]
可能是因为接口升级的原因，暂且先改成“结束”吧
