### ISSUE TITLE
执行`一键配置环境`时，会提示依赖有冲突

### ISSUE THREAD

**Issue by skyls03** [ninthDevilHAUNSTER/ArknightsAutoHelper#254]
执行`一键配置环境`时，会提示依赖有冲突
![image](https://user-images.githubusercontent.com/45219522/132293573-8f57956a-4fa0-4d72-ac43-1e592586701b.png)

**Comment by triwinds** [comment]
mxnet 那两个的依赖报错似乎对运行没什么影响吧？
