### ISSUE TITLE
有没有人在 WSL里跑助手， 模拟器开在本机的

### ISSUE THREAD

**Issue by Vela-zz** [ninthDevilHAUNSTER/ArknightsAutoHelper#272]
如何设置adb连接 求点经验

**Comment by dantmnf** [comment]
WSL1 可以直接连接模拟器端口，WSL2 需要设置一下端口转发，把模拟器的 adb 端口转发到 WSL，比如
`netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=5556 connectaddress=127.0.0.1 connectport=5555`
然后在 WSL 里 `adb connect 172.___.___.1:5556` 。
WSL2 的 IP 地址每次启动都会变化，微软没有任何想要实现固定 IP 地址的打算：https://github.com/microsoft/WSL/issues/4210 。

**Comment by ryocown** [comment]
Use case比较类似remote debug，可以参考
1. [Medium](https://pellea.medium.com/using-adb-with-wsl2-7aebbb070a47)
2. [SO](https://stackoverflow.com/questions/60166965/adb-device-list-empty-using-wsl2)
3. [Gist](https://gist.github.com/bergmannjg/461958db03c6ae41a66d264ae6504ade)

WSL2的loopback是跑在Hyper-V Virtual Ethernet Adapter上的，所以还需要把Private Firewall给disable掉。
以上guide都是基于WSL2+Android Studio，对于其他模拟器支持如何还得测试。
