### ISSUE TITLE
akhelper-gui.exe无法运行

### ISSUE THREAD

**Issue by guojunyu196** [ninthDevilHAUNSTER/ArknightsAutoHelper#275]
![KRQR1H%18 $18GW}{7XV`O5](https://user-images.githubusercontent.com/76220347/141684467-8db778e2-937a-4bbd-a1e7-74fd2ba2d0ca.png)
akhelper.exe可正常运行，akhelper-gui.exe无法运行

**Comment by woner363** [comment]
我也一样

**Comment by dantmnf** [comment]
本地打出来的包是好的，感觉是 CI 炸了

**Comment by guojunyu196** [comment]
每次下载完解压时就会提示该文件已损坏，是不是压缩包的问题，有没有其他下载
![H90P8I0D{I I(X_%9DDWB_M](https://user-images.githubusercontent.com/76220347/142769296-5e661160-dcba-4779-8e1c-e374562a8bd2.png)
方式

**Comment by dantmnf** [comment]
压缩包是 LZMA 算法的 zip，符合 zip 标准，7z/WinZip/WinRAR 都可以正常解压。

**Comment by guojunyu196** [comment]
![MJSIU}1_8GXUVACVBKE{B`J](https://user-images.githubusercontent.com/76220347/142769514-95c4ac3c-07bf-4722-becc-4252ead5bc19.png)
7zip也不行，我试试WinRAR

**Comment by guojunyu196** [comment]
![QQ截图20211122000651](https://user-images.githubusercontent.com/76220347/142769596-be0ab2ed-81a4-4ec7-bb58-5dd077344e6d.png)

**Comment by dantmnf** [comment]
那应该是下载坏了，文件大小应该在 40M 左右

**Comment by guojunyu196** [comment]
下了好几次了，都这样，有其他下载方式吗

**Comment by dantmnf** [comment]
看起来是 ci 里的 python.exe 少了 manifest，然后 pyinstaller 生成了一个有问题的：https://github.com/pyinstaller/pyinstaller/pull/6367

现在 CI 的二进制包会额外传到 Releases 里面，~~虽然不挂梯子应该还是下载不来~~

**Comment by guojunyu196** [comment]
找到下载的方法了，有遇到相同问题的同志可以去tb花一两块找个代下载
