### ISSUE TITLE
在 linux 下无法正确自动检测/连接 adb 设备

### ISSUE THREAD

**Issue by CX03-a** [ninthDevilHAUNSTER/ArknightsAutoHelper#286]
版本号 ：master-904+ba56413-dirty
系统 ：arch linux
python version ：3.10.1

具体表现为自动检测出来的设备不存在
且无法连接到已经开启adb调试的设备
![2022-01-02 17-39-15 的屏幕截图](https://user-images.githubusercontent.com/42435544/147872014-d7aa55a5-a70c-4487-9be0-fd62e36ccc4e.png)

**Comment by dantmnf** [comment]
看起来像是 worker 死了，终端里是否有报错信息？

**Comment by jylc** [comment]
我也遇到了相同的问题，把config.yaml的22行"bluestacks_hyperv:"注释就行了，自动探测 BlueStacks Hyper-V 的 ADB 端口的时候会读取dll文件导致异常抛出。

**Comment by tkkcc** [comment]
archlinux+genymotion测了能自动连接模拟器刷1-7。
其他功能还没测，先打包了[aur](https://aur.archlinux.org/packages/akhelper-git/)。
