### ISSUE TITLE
关于只能使用powershell执行的问题

### ISSUE THREAD

**Issue by ArsKoe** [ninthDevilHAUNSTER/ArknightsAutoHelper#287]
今天心血来潮pull了一下更新，然后原本的方式不能用了
我原本是在桌面为akhelper.py创建了一个快捷方式，现在双击快捷方式无用，在原本文件夹中双击akhelper.py也无用，只能通过用powershell运行
`python akhelper.py`
来打开。后来发现用cmd执行上述命令结果就是如下：
![微信截图_20220103000910](https://user-images.githubusercontent.com/65359735/147881801-18839d50-ab77-49c9-8972-08eab67ba819.png)
程序初始化似乎不成功，但使用powershell就没问题
![微信截图_20220103000957](https://user-images.githubusercontent.com/65359735/147881821-88d23e8b-6fd7-4089-bea1-1b1e18593e5e.png)
我在网络上并没有找到关于这种只能用powershell运行不能用cmd运行的原因，也许和脚本内部代码有关？能请帮忙解答一下吗？谢谢

**Comment by dantmnf** [comment]
看看 cmd 里 `where python` 和 powershell 里 `Get-Command python` 是否指向同一个文件？

**Comment by ArsKoe** [comment]
看了一眼指向的文件没问题，目前是通过git暂且回滚到上个版本就解决了这个问题，后续我再找找这个问题根源吧，谢谢了
