### ISSUE TITLE
连接设备时抛出 EOFError: recvexactly 4 bytes failed 

### ISSUE THREAD

**Issue by My-stery** [ninthDevilHAUNSTER/ArknightsAutoHelper#288]
目前使用的是 BlueStacks ,前几天刚卸载了mumu ，然后 pull 了下更新之后试了 auto grass 就抛出了错误，结果现在连快速的时候也一样抛出错误了，也不知道哪里错了。
![image](https://user-images.githubusercontent.com/34577331/148233346-9a64d1f2-713c-4be0-bea5-50bbfd981e13.png)

**Comment by dantmnf** [comment]
检查 bluestacks 设置里是否打开了 adb

**Comment by My-stery** [comment]
> 检查 bluestacks 设置里是否打开了 adb

是开启的，以前也能用上

**Comment by dantmnf** [comment]
看了一下 stack，可能是 adb server 炸了。可以尝试先结束所有 adb 进程，然后检查命令行 adb shell 能不能用。

**Comment by My-stery** [comment]
> 看了一下 stack，可能是 adb server 炸了。可以尝试先结束所有 adb 进程，然后检查命令行 adb shell 能不能用。

惊了，找到占用的地方了，以前也没出现过这种事情的，这个软件莫名占用了端口
![image](https://user-images.githubusercontent.com/34577331/148236047-c64a65ba-c363-486b-ba0c-fc3cfb9eecda.png)
![image](https://user-images.githubusercontent.com/34577331/148236186-4171e9bb-1e01-4c80-bf8b-8ca3a18aa3f1.png)
