### ISSUE TITLE
是否有计划增加集成战略的功能

### ISSUE THREAD

**Issue by UVJkiNTQ** [ninthDevilHAUNSTER/ArknightsAutoHelper#291]
RT，主要是存商店投资系统

**Comment by AO2233** [comment]
1. 有四项资源需要爆肝，分别是`收藏品`和`商店投资系统`，`等级`和`灵感`。
**2.** 第一层必有商店，投资在第一层出现，代表本局有投资系统存在，且事实上第一层就能存满。出现投资系统的概率大概是30%左右。通过第一层的过程中就可以收集上述资源。
3. 守门流（蓝门）可以过第一层。

根据这些特性，可以用 opencv 识别蓝门，实现自动战斗，文字识别（本人使用的是 paddleocr）实现流程控制。
写了个简单的 demo:
[演示视频传送门](https://www.bilibili.com/video/BV1bq4y1c7Pn/)

但是如果后续**第2点**发生变化，比如机制变化，第一层没有商店了，仅有第二层以上有商店等`加肝行为`，
那么自动程序难度就很大了，不仅要实现智能战斗，而且收益很低，就目前而言，手动操作一轮都要3分钟，程序肯定比这个慢，挂10把就是一小时。如果后续变得更肝、机制变化，现在即使写一个，之后也没有太大意义了。

希望日后肉鸽机制稳定了以后，能加入对集成战略的支持。

**Comment by UVJkiNTQ** [comment]
用山写了个zjs把投资攒满了，暂时没需求了

收藏品在哪层出现看似没有规律

**Comment by UVJkiNTQ** [comment]
看到新的PR了，关了
