### ISSUE TITLE
使用WSA运行方舟，akhelper无法正常捕捉到关卡画面

### ISSUE THREAD

**Issue by NineMeowHL** [ninthDevilHAUNSTER/ArknightsAutoHelper#299]
如题

**Comment by HTLXMC** [comment]
我使用的是MagiskOnWSA项目编译的WSA，版本是最新的

**Comment by Radekyspec** [comment]
#268

**Comment by HTLXMC** [comment]
> #268

怎么弄

**Comment by TNXG** [comment]
wsa的问题，等微软修复吧，老早就有的问题了

**Comment by HTLXMC** [comment]
> > wsa的问题，等微软修复吧，老早就有的问题了
> 
> 草，修好了啊，那没事了

看是修好了，但是我怎么还是会出现这个问题……

**Comment by dantmnf** [comment]
WSA 还需要一些额外操作来正确截取游戏画面，在上面那个 issue 里 track 吧。
