### ISSUE TITLE
实际使用的时候出的一些问题&建议

### ISSUE THREAD

**Issue by ZhouZiHao-Moon** [ninthDevilHAUNSTER/ArknightsAutoHelper#38]
①可能会出现一个任务结束之后返回主页弹出维护公告的情况，建议加上在主页时对公告的处理。
②任何出现的不在预料中页面的情况都可以通过返回主页的形式修复……吧（刚刚它点到了招募差点把我的石头花了，幸好我石头不够），至少也不要尝试修复失败就直接当无事发生打关……

**Comment by Prurite** [comment]
关于第二条：任何错误都可以通过重启明日方舟解决，除非是闪断更新或者脚本自身错误（

**Comment by ZhouZiHao-Moon** [comment]
然而那还要重新登陆，也不是个办法……
owner好像说过不会添加登录的功能（怕被人说盗号）
都开源了盗不盗的自己看看不就好了……

**Comment by Prurite** [comment]
登录的意思不是自动点登录按钮吗…… 要是自动填写账号密码就确实有点那个了

**Comment by ZhouZiHao-Moon** [comment]
我的issue我自己已经填了……
等owner merge……
