### ISSUE TITLE
ADBdevice 连接远程手机没有反应

### ISSUE THREAD

**Issue by PPPHUB** [ninthDevilHAUNSTER/ArknightsAutoHelper#390]
from automator.control.adb.client import ADBClientSession, ADBDevice,ADBServer
s=ADBServer(("11.4.196.11",30770))
a=ADBDevice(server=s)
a.exec("mkdir /data/local/tmp/socket") 

程序会一直运行没有输出

**Comment by dantmnf** [comment]
ADBServer 不是手机的 ADB 端口，不确定请留空或使用 ADBServer.DEFAULT。

设备的 ADB 端口需要在 ADBClient 的 serial 中指定。
