### ISSUE TITLE
base.py检查ocr的部分好像不太对劲

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#4]
在__is_ocr_active中，这个尝试识别后结果保存在 SCREEN_SHOOT_SAVE_PATH

`os.popen(
            "tesseract {} {}".format(
                STORAGE_PATH + "OCR_TEST_1.png", SCREEN_SHOOT_SAVE_PATH + "1"
            )
        )`

但是接下来检测时，并没有从SCREEN_SHOOT_SAVE_PATH读文件，而是读取了STORAGE_PATH 的文件
`open(STORAGE_PATH + "ocr_test.txt", 'r', encoding="utf8")`

PS:第一次用ocr我是不是安装姿势不正确，自己手动尝试识别失败

**Comment by ninthDevilHAUNSTER** [comment]
因为我OCR模块装好了，所以这边的代码测试好像有些问题，我会在下次进行修改。谢谢提醒
