### ISSUE TITLE
Baidu ocr 无法识别“7”

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#41]
绝了原图75票数只能识别5
![strength](https://user-images.githubusercontent.com/19811879/64050430-03002080-cb46-11e9-91e4-4d8203588016.png)
但是，处理后可以识别
![strength](https://user-images.githubusercontent.com/19811879/64050447-0dbab580-cb46-11e9-85a6-56edd30235c9.png)
**这个问题不是第一次出现了**，我的想法是识别前处理所有
解决方案
1. 全局统一设定，不区分是否使用百度ocr，你们怎么看
2. 如果这样选择1的话还可能需要新的图片处理算法，原来的有些简陋，但可能需要新的库比如opencv ~~不是很确定，我并没有详细了解过图片处理
3. tesseract可以支持训练字体库，我不确定有没有必要弄一个

**Comment by ninthDevilHAUNSTER** [comment]
①用PIL可以解决，不用opencv,但是灰度二值化已经在大多数情况下足够，你要不加个滤波？
②有些用户应该会用百度api，本地并不装tesseract。有些人只用tesseract不用百度API比如我
③所以结论是百度API还没tesseract好用？？？？

**Comment by LittleNightmare** [comment]
> ①用PIL可以解决，不用opencv,但是灰度二值化已经在大多数情况下足够，你要不加个滤波？
> ②有些用户应该会用百度api，本地并不装tesseract。有些人只用tesseract不用百度API比如我
> ③所以结论是百度API还没tesseract好用？？？？

1. 灰度值二值化，其中那个阈值 ~~是这个名字吧~~ 我自己随便选的，只使用PIL我找不到可以 ~~抄~~ 学习的自适应阈值PIL所以这个值可能出问；滤波用吗，我觉图片本身质量不低

2. 百度api比tesseract用起来至少安装简单点，但是百度api很迷，特定情况无法识别，tesseract不知道为啥每个人表现不太一样，我记得我的就不太好识别

3. 我觉得在黑底白字的图像上，tesseract表现的错误正常点，百度api感觉是个半残 ~~每次都只消失第一个字符~~
**result**
我先把二值化不区分百度api还是tesseract，通过base里传递的参数控制吧，应该不用弄到config里
