### ISSUE TITLE
主战斗模块ToDoList

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#44]
这里list了建议支持的的关卡列表，列表参考了来着nga论坛[攻略](https://bbs.nga.cn/read.php?tid=17749128)

![](https://img.nga.178.com/attachments/mon_201908/15/-klbw3Q5-d1lnZmT3cSyw-gy.png)

列表从左到右，从上到下
- [ ] 4-9
- [x] 2-10
- [x] 3-2
- [x] 4-7
- [ ] 4-8
- [ ] 3-3
- [x] 4-6
- [x] 3-1
- [x] 4-5
- [ ] 5-8
- [ ] S4-1
- [x] 3-4
- [ ] 4-10
- [x] 5-10
- [x] 4-4
- [ ] 3-8
- [x] 5-3
- [ ] 4-2
- [ ] S4-6
- [x] 1-7
- [ ] 3-7
- [ ] 5-7
- [ ] S3-3
- [ ] S3-4
- [ ] S3-2
- [x] 5-3
- [ ] S3-1
- [ ] S4-9
- [x] 2-6
- [ ] S2-5
- [x] 4-5
- [ ] S2-9
- [ ] 2-5
- [ ] S2-8
- [x] 2-6
- [ ] 2-3
- [ ] 3-8
- [ ] S2-7
- [ ] 2-5
- [ ] S2-6

感觉好多啊，是不是应该换一个方式储存什么的
如果全部实现后，也许可以开发一个根据材料选关的方法或者直接访问现有的网页工具 ~~目前我看到了三波人~~

**Comment by LittleNightmare** [comment]
北京时间12:09 update列表

**Comment by Prurite** [comment]
其实可以先把 battle_slim 优化一下？做到人选到关之后自动识别当前关卡一键开始战斗，不再需要手动传入关卡id啥的

**Comment by fatinghenji** [comment]
更新新的支持列表了吗？
