### ISSUE TITLE
关于判定是否在关卡页面

### ISSUE THREAD

**Issue by ZhouZiHao-Moon** [ninthDevilHAUNSTER/ArknightsAutoHelper#55]
可以使用OCR检测当前关卡名，这样比代理作战的图片识别更准确。不使用OCR的话就还是用代理指挥的图片吧。
PS：为什么确认当前代理指挥的时候只识别一个方框不带上字？

**Comment by ninthDevilHAUNSTER** [comment]
因为代理只会是用的图片判断的，那个小方框点上和不点上差很大。
目前代理只会方面没啥问题【有也是二值化搞得】，所以不掉OCR了。
明显灰度分布算法会速度更快

**Comment by LittleNightmare** [comment]
现在都是有的，不过跟确认代理指挥开启分开了，因为ocr部分无法检测是否开启代理指挥
