### ISSUE TITLE
截图的问题

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#6]
当理智超过100后，截图缺一部分，在我的ocr中，会变得无法识别
![strength](https://user-images.githubusercontent.com/19811879/58440278-f1bafa00-80a6-11e9-8006-6bfeb6ec9db9.png)
之前我更改了有关ocr的命令，因为默认函数无法识别我的截图
`tesseract {} {} --psm 7`
可能是我的版本问题，推荐版本我安装失败，安装了4.0版本。

**Comment by ninthDevilHAUNSTER** [comment]
今天有空我会改大点参数位置，顺便把ocr的函数给写出来方便你们手动修改与之后gui调优
