### ISSUE TITLE
待修的小 bug & 一些预想的 feature 表

### ISSUE THREAD

**Issue by Prurite** [ninthDevilHAUNSTER/ArknightsAutoHelper#70]
如题，欢迎各位 pr。

### Bug

- [ ] `clear_daily_task` 函数在关闭 ocr 的情况下会用到的 `TASK_COMPLETE` 和 `REWARD_GET` 图片缺失
- [ ] 部分关卡和按钮的取点错误（如 1-7 ），建议整个脚本重新取点

### New Feature

- [x] 在 battle_slim 中加入自动识别当前关卡所需理智功能，做到一键开始战斗
- [x] 保存每次战斗后的掉落截图，方便统计刷关情况
  - [ ] 远期目标：与企鹅物流合作
- [ ] 整理最近的新代码，统一格式
- [ ] 统一日志格式

**Comment by AndyChen2005121** [comment]
统计刷关情况的话... 个人认为还可以和penguin-stats.io集成,加一个自动上报材料掉落(???)

**Comment by Prurite** [comment]
> 统计刷关情况的话... 个人认为还可以和penguin-stats.io集成,加一个自动上报材料掉落(???)

其实我是有这样的设想的，但是担心比如他们抗议我们这边有人滥用他们的API，或者用户不愿意上报

**Comment by LittleNightmare** [comment]
话说你们遇到关卡奖励领取停不下来吗....我觉得是752行的锅，我正在测试

**Comment by ninthDevilHAUNSTER** [comment]
也许可以和人家企鹅数据的交流一下？
咱们现在也发布了 相对比较稳定的版本了，尽管代码修修补补看上去良莠不齐....
而且咱们还需要掉落识别啥的

**Comment by Prurite** [comment]
> 也许可以和人家企鹅数据的交流一下？
> 咱们现在也发布了 相对比较稳定的版本了，尽管代码修修补补看上去良莠不齐....
> 而且咱们还需要掉落识别啥的

相对稳定（
我觉得国庆可以再大规模重构一下，这半个月改的东西有点多，现在代码太乱了啊
最好顺便弄个guideline和文档，当然这又是个巨坑

**Comment by LittleNightmare** [comment]
自动消耗安排上了，但是我一直不知道怎么起用window OCR

**Comment by LittleNightmare** [comment]
> 话说你们遇到关卡奖励领取停不下来吗....我觉得是752行的锅，我正在测试

  这个也在这次pull #73 里修复了

**Comment by LittleNightmare** [comment]
> 也许可以和人家企鹅数据的交流一下？
> 咱们现在也发布了 相对比较稳定的版本了，尽管代码修修补补看上去良莠不齐....
> 而且咱们还需要掉落识别啥的

那个企鹅我不知道为啥，我登录永远404

**Comment by leng-yue** [comment]
是不是可以做 输入材料后自动走企鹅规划, 然后刷图

**Comment by ElgoogUdiab** [comment]
> 是不是可以做 输入材料后自动走企鹅规划, 然后刷图

或者在刷图的时候指定刷出N个材料啥的

**Comment by xiaommQF** [comment]
几个个人感觉可以优化的地方：
 1.理智部分，舍弃当前理智输入选项，可以采用进入关卡，在正式开始前配合CV2截图识别特征色块判断理智剩余情况
 同理，根据当理智药不充足时自动跳转到源石补充理智界面的特性，可以判断是否有理智药剩余

**Comment by poly000** [comment]
反检测有没有做？

**Comment by gypsyzz** [comment]
能不能自动滚动窗口最下面的当前状况? 没有也无碍
