### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by LittleNightmare** [ninthDevilHAUNSTER/ArknightsAutoHelper#71]
```
Traceback (most recent call last):
  File "E:/GitHub/ArknightsAutoHelper/start.py", line 11, in <module>
    Ark = ArknightsHelper(adb_host=ADB_HOST)
  File "E:\GitHub\ArknightsAutoHelper\Arknights\base.py", line 43, in __init__
    self.adb = ADBShell(adb_host=adb_host)
  File "E:\GitHub\ArknightsAutoHelper\ADBShell.py", line 33, in __init__
    self.DEVICE_NAME = self.__adb_device_name_detector()
  File "E:\GitHub\ArknightsAutoHelper\ADBShell.py", line 39, in __adb_device_name_detector
    devices = self.host_session_factory().devices()
  File "E:\GitHub\ArknightsAutoHelper\ADBShell.py", line 32, in <lambda>
    self.host_session_factory = lambda: ADBClientSession(ADB_SERVER)
  File "E:\GitHub\ArknightsAutoHelper\ADBClientSession.py", line 43, in __init__
    sock.connect(server)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
```

**Comment by LittleNightmare** [comment]
emmm我把杀软，关了再开一下好了

**Comment by dantmnf** [comment]
adb server 没开或者被杀了
可以加个异常处理然后自己 adb start-server

**Comment by LittleNightmare** [comment]
> adb server 没开或者被杀了
> 可以加个异常处理然后自己 adb start-server
我开资源管理器看了。。。。adb打开了

**Comment by Prurite** [comment]
问题还有吗

**Comment by LittleNightmare** [comment]
> 问题还有吗

有的，而且单纯把杀软（我的是火绒）关了不行，必须关了重开，鬼知道怎么回事

**Comment by dantmnf** [comment]
试试加到白名单？

**Comment by LittleNightmare** [comment]
> 试试加到白名单？

似乎不好使，我填了个文件夹，并且我用pycharm建立venv在改目录下，而且这次开关不好使，开关一次后，又关上好用的

**Comment by dantmnf** [comment]
> 我填了个文件夹，并且我用pycharm建立venv在改目录下

要加 python.exe

**Comment by LittleNightmare** [comment]
> > 我填了个文件夹，并且我用pycharm建立venv在改目录下
> 
> 要加 python.exe

没用。。。。我都加了

**Comment by Prurite** [comment]
自己测试了一下，发生这种情况可能是因为adb的默认端口（5037）被占用，解决方案：
```
netstat -aon|findstr "5037"
```
获取占用 5037 端口的进程的 pid ，结束该进程后重新
```
adb start-server
```
问题即解决。

**Comment by LittleNightmare** [comment]
> 自己测试了一下，发生这种情况可能是因为adb的默认端口（5037）被占用，解决方案：
> 
> ```
> netstat -aon|findstr "5037"
> ```
> 
> 获取占用 5037 端口的进程的 pid ，结束该进程后重新
> 
> ```
> adb start-server
> ```
> 
> 问题即解决。

俺寻思不太对劲...好像是我adb压根没有起动....
![image](https://user-images.githubusercontent.com/19811879/65730150-d0870c00-e08e-11e9-8229-f8f3f9f4204e.png)
然后我直接执行adb....
![image](https://user-images.githubusercontent.com/19811879/65730244-1e9c0f80-e08f-11e9-94ee-14707daa8979.png)
结果就好了.....
完全搞不明白，跟我杀软有什么关系

**Comment by Prurite** [comment]
> 俺寻思不太对劲...好像是我adb压根没有起动....
> ![image](https://user-images.githubusercontent.com/19811879/65730150-d0870c00-e08e-11e9-8229-f8f3f9f4204e.png)
> 然后我直接执行adb....
> ![image](https://user-images.githubusercontent.com/19811879/65730244-1e9c0f80-e08f-11e9-94ee-14707daa8979.png)
> 结果就好了.....
> 完全搞不明白，跟我杀软有什么关系

嗯 我测试的时候是无法启动 adb ，原因端口被占用…… 反正问题解决了是吧

**Comment by LittleNightmare** [comment]
> 嗯 我测试的时候是无法启动 adb ，原因端口被占用…… 反正问题解决了是吧

...算是吧，我可能需要每次都启动一下，好惨

**Comment by dantmnf** [comment]
会不会是 adb server 没有开在默认端口？

**Comment by LittleNightmare** [comment]
> 会不会是 adb server 没有开在默认端口？

emmm这个怎么查，我用的夜神，刚刚我`kill-server`然后在夜神的文件夹的adb又开了一下显示还在`5037`

**Comment by LittleNightmare** [comment]
> 会不会是 adb server 没有开在默认端口？

等下，我看了下这个好像有思路了[https://bbs.csdn.net/topics/390870699](url)我怀疑是前天测试华为手机装了个华为手机助手的锅，我卸载下，然后试试，一会update

**Comment by dantmnf** [comment]
端口号可以用环境变量改，可以看看夜神自己开的 adb listen 了哪个端口（用 netstat 或者 resmon

**Comment by LittleNightmare** [comment]
> 环境变量可以临时设置，可以看看夜神自己开的 adb listen 了哪个端口（用 netstat 或者 resmon

我发现我的nox_adb.exe不断地启动终止再启动。。。。。我大概有6个，似乎是端口有占用，但通过netstat发现，有时候会有两个nox_adb.exe抢这个端口状态是`SYN_SENT`

**Comment by dantmnf** [comment]
不断启动应该是在跑命令吧~~我们比夜神先进了~~~，SYN_SENT 代表在尝试连接 server

**Comment by LittleNightmare** [comment]
我配置了fibbler抓https包后，可以直接连接了......但是每次虽然不影响登陆，但明日方舟会网络检查失败但可以连接
```
1. fibbler开启抓https
2. 本地安装证书
3. 打开代理（系统）
4. 模拟器设置网络代理
5. 模拟器安装证书
```

**Comment by LittleNightmare** [comment]
问题原因已经发现，似乎是由于adb的版本更新导致的错误，我曾经更换过adb ``1.0.38``的版本导致的错误；然后这次我用最新的adb版本``1.0.41``会导致直接完全失败，即使重新启动也无法找到任何设备；我重新覆盖安装夜神后发现adb正确版本为``1.0.36``其他版本似乎会导致奇奇怪怪的错误，具体原因未知，准备pr

**Comment by LittleNightmare** [comment]
现在我只弄通过夜神目录下的nox_adb.exe才能成功开启

**Comment by LittleNightmare** [comment]
把adb在模拟的安卓系统里重新开关一下可以解决
