### ISSUE TITLE
后续计划

### ISSUE THREAD

**Issue by dantmnf** [ninthDevilHAUNSTER/ArknightsAutoHelper#74]
- [x] 按比例确定截图/点击位置，同时支持更多的宽高比（UI 元素大小主要与高度有关，水平对齐方式基本上是整块靠左中右）
- [x] (80%) 进行特定字体/特定字符特化的识别，目前的通用 OCR 仅作为备用
- [x] 基于图像识别（模板匹配）的关卡选择（有 prototype，主要是缺各个关卡的定位数据和截图）
- [x] (90%) 物品（掉落）识别
- [x] 公开招募识别

**Comment by dantmnf** [comment]
prototype: https://github.com/dantmnf/akimgreco

**Comment by Prurite** [comment]
公开招募……？emmm 感觉会让脚本变得臃肿了吧，毕竟现在现成的公开招募计算器不少

**Comment by GachaSalt** [comment]
贴一条结算界面的识别demo （不依赖OCR）
https://github.com/GachaSalt/Arknights-Drop-Recognition

可对全主线（除了剿灭作战）进行识别。
识别内容：
关卡名称
掉落物品及数量
等级
经验值

**Comment by dantmnf** [comment]
> 按比例确定截图/点击位置，同时支持更多的宽高比（UI 元素大小主要与高度有关，水平对齐方式基本上是整块靠左中右）

部分界面在小于 16:9 (?)的宽高比上会产生垂直 margin/padding（e.g. iPad 上的截图），目前假定宽高比不小于 16:9
