### ISSUE TITLE
与企鹅物流的联动

### ISSUE THREAD

**Issue by Prurite** [ninthDevilHAUNSTER/ArknightsAutoHelper#86]
https://github.com/penguin-statistics/frontend-v2/issues/158 企鹅物流方面已对我们的脚本做出了积极的回应。所以谁去实现这个功能呢

**Comment by dantmnf** [comment]
blocked by #87

**Comment by dantmnf** [comment]
这个 issue 应该可以关了？

**Comment by Prurite** [comment]
等 merge 到 master 之后再关吧
