### ISSUE TITLE
重构 config 接口

### ISSUE THREAD

**Issue by dantmnf** [ninthDevilHAUNSTER/ArknightsAutoHelper#87]
为了在企鹅数据网站上查询统计结果，调用企鹅数据 API 时需要提供 user id，如果没有提供，则 API 会生成并返回一个新的 user id，需要对其进行持久化存储（写入配置文件）。

同时，配置文件需要保持人类可读，最好在写入时能保留注释。

~~先把坑放在这~~

**Comment by AlvISsReimu** [comment]
补充：查询**全平台**的统计结果矩阵是不需要userID的，详见[API文档](https://penguin-stats.io/PenguinStats/swagger/swagger-ui.html)里`result-controller`的`Get matrix`。查询某用户的掉落矩阵时（`is_personal `为`true`）则需要userID。
